#!/usr/bin/env bash
# Fails a PR that bumps a version or touches a release artefact by hand.
# Versions and CHANGELOG.md only ever change via the Release PR workflow
# (.github/workflows/release-pr.yml); see docs/releasing.md.
#
# Usage: check-no-version-bump.sh <base-sha> <head-sha>
# Env:
#   PR_HEAD_REF  - the PR's head branch name. A release/v* branch is exempt
#                  (that's the one place these artefacts are meant to
#                  change). This is a convenience, not a security boundary —
#                  it's keyed on the branch name alone, and anyone who can
#                  push a branch can already edit this workflow.
#
# Operates on the caller's cwd git repo (see check-fragment.sh's comment on
# the same choice); sourced by test-checks.sh, guarded at the bottom by
# PAWL_RELEASE_CHECK_TEST like check-fragment.sh.
set -euo pipefail

pr_head_is_release_branch() {
  local ref="$1"
  case "$ref" in
    release/v*) return 0 ;;
    *) return 1 ;;
  esac
}

changie_config_exists_at() {
  local rev="$1"
  git cat-file -e "${rev}:.changie.yaml" 2>/dev/null
}

# diff_touches_changelog BASE HEAD
diff_touches_changelog() {
  local base="$1" head="$2"
  local touched
  touched=$(git diff --name-only "$base" "$head" -- 'CHANGELOG.md')
  [ -n "$touched" ]
}

# diff_touches_release_notes BASE HEAD
# Any add/modify/delete of a .changes/v*.md release-notes file.
diff_touches_release_notes() {
  local base="$1" head="$2"
  local touched
  touched=$(git diff --name-only "$base" "$head" -- '.changes/v*.md')
  [ -n "$touched" ]
}

# plugin_version_at REV
# Empty string if the file doesn't exist at that rev.
plugin_version_at() {
  local rev="$1"
  git show "${rev}:.claude-plugin/plugin.json" 2>/dev/null | jq -r '.version // empty' 2>/dev/null || true
}

# diff_bumps_plugin_version BASE HEAD
# Fails (in the "problem found" sense, i.e. returns 0) only when the file
# exists at both revisions and its .version field differs — a file that's
# missing on either side, or any other plugin.json edit, is not this
# check's business.
diff_bumps_plugin_version() {
  local base="$1" head="$2"
  local before after
  before=$(plugin_version_at "$base")
  after=$(plugin_version_at "$head")
  [ -n "$before" ] && [ -n "$after" ] && [ "$before" != "$after" ]
}

check_no_version_bump() {
  local base="$1" head="$2"
  local head_ref="${PR_HEAD_REF:-}"

  if pr_head_is_release_branch "$head_ref"; then
    echo "ok: release branch ($head_ref) is where these artefacts are meant to change"
    return 0
  fi

  if ! changie_config_exists_at "$base"; then
    echo "ok: bootstrap (.changie.yaml doesn't exist at base) — this PR introduces the changelog system"
    return 0
  fi

  local failed=0

  if diff_touches_changelog "$base" "$head"; then
    echo "FAIL: this PR touches CHANGELOG.md. CHANGELOG.md is generated by 'changie merge' in the Release PR workflow — never edit it by hand." >&2
    failed=1
  fi

  if diff_touches_release_notes "$base" "$head"; then
    echo "FAIL: this PR adds, modifies, or deletes a .changes/v*.md release-notes file. Those are written by 'changie batch' in the Release PR workflow." >&2
    failed=1
  fi

  if diff_bumps_plugin_version "$base" "$head"; then
    echo "FAIL: this PR changes .claude-plugin/plugin.json's \"version\" field. Versions are bumped only by the Release PR workflow's changie 'replacements:' — never by hand in a normal PR." >&2
    failed=1
  fi

  if [ "$failed" -eq 0 ]; then
    echo "ok: no release artefact was touched by hand"
    return 0
  fi
  return 1
}

main() {
  if [ "$#" -ne 2 ]; then
    echo "usage: check-no-version-bump.sh <base-sha> <head-sha>" >&2
    exit 1
  fi
  check_no_version_bump "$1" "$2"
}

if [ "${PAWL_RELEASE_CHECK_TEST:-0}" != "1" ]; then
  main "$@"
fi
